name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run YAML linting
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: |
            *.yml

  Up-Down:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bring up and shut down services
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yml
          compose-flags: |
            --env-file .env.ci
