on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'bihealth'
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: simple
